### PR TITLE
PrivateEvents Project for Microverse.

### PR DESCRIPTION
**Pull request by FdI96**
We implemented these functionalities below:

User:
-Sign Up.
-Sign In.
-Sign Out.
-Create an event.
-Attend an event.

Events:
-Can be created.
-Attended.

We implemented a many-to-many association through an Attendance table to handle the event's attendance for the Users.

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 
**This is a great project you have going on, well-done lads. The readme file is clear and concise 👍🏽**. However, there are a few issues to fix to get approved.

### REQUIRED CHANGES: ⚠️ 

- [x] When a user is not signed in, they are able to see the attend button of upcoming events, on clicking, an error is raised.
Screenshot from 2021-04-13 02-22-54

- Almost the same error is raised when they try to edit an event when not signed in.

> SOLUTION is to show only the event names and exclude all other privileges( attend button, edit and show links).

- [x] Currently, users that didn't create an event are able to edit the event info. This shouldn't be the expected app behavior. Only event creators should have the edit privilege.
- [x] Once a user is listed as an attendee to the event, when the attend button is clicked, an error is raised. Remove/hide the attend button is a user is already attending the event.
- [x] The create action in the events controller should use `build` method on association, i.e. current_user.events.build(event_params) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [x] The index action in the events controller should lists past events, i.e. @past_events = Event.previous_events ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- [x] The index action in the events controller should list upcoming events, i.e. @upcoming_events = Event.upcoming_events ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [x] The show action in users controller should list events created by user, i.e. @created_events = current_user.events (screenshot from Odin)

- [x] The show action in users controller should list events events previoulsy attendented by user using event model scope, i.e. @past_events = current_user.attended_events.previous (screenshot from Odin)

- [x] The show action in users controller should list events upcoming events previously attended by user using event model scope, i.e. @upcoming_events = current_user.attended_events.upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [x] You are currently having only association tests for your models. Add integration tests for your authentication and event management. You may choose to use Capybara along with Rspec. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

 

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Ping me on slack for a chit-chat 🆘  Roy Mukuye Or mention me in this PR

**Comment by FdI96** [comment]
> # STATUS: CHANGES REQUIRED 🔴 ♻️
> ## Hey Happy Coders, 👋🏽
> **This is a great project you have going on, well-done lads. The readme file is clear and concise 👍🏽**. However, there are a few issues to fix to get approved.
> 
> ### REQUIRED CHANGES: ⚠️
> * [x]  When a user is not signed in, they are able to see the attend button of upcoming events, on clicking, an error is raised.
>   Screenshot from 2021-04-13 02-22-54
> * Almost the same error is raised when they try to edit an event when not signed in.
> 
> > SOLUTION is to show only the event names and exclude all other privileges( attend button, edit and show links).
> 
> * [x]  Currently, users that didn't create an event are able to edit the event info. This shouldn't be the expected app behavior. Only event creators should have the edit privilege.
> * [x]  Once a user is listed as an attendee to the event, when the attend button is clicked, an error is raised. Remove/hide the attend button is a user is already attending the event.
> * [x]  The create action in the events controller should use `build` method on association, i.e. current_user.events.build(event_params) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
> * [x]  The index action in the events controller should lists past events, i.e. @past_events = Event.previous_events ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
> * [x]  The index action in the events controller should list upcoming events, i.e. @upcoming_events = Event.upcoming_events ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
> * [x]  The show action in users controller should list events created by user, i.e. @created_events = current_user.events (screenshot from Odin)
> * [x]  The show action in users controller should list events events previoulsy attendented by user using event model scope, i.e. @past_events = current_user.attended_events.previous (screenshot from Odin)
> * [x]  The show action in users controller should list events upcoming events previously attended by user using event model scope, i.e. @upcoming_events = current_user.attended_events.upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
> * [x]  You are currently having only association tests for your models. Add integration tests for your authentication and event management. You may choose to use Capybara along with Rspec. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
> 
> ### Kindly make all the requested changes and submit another CRR. 💯
> **Cheers 🍹 and Happy coding 💻**
> 
> ## Ping me on slack for a chit-chat 🆘 Roy Mukuye Or mention me in this PR

Awesome review, thanks a lot for it. Very helpful

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 
**Thanks for implementing the changes requested earlier on**. However, there is one more issue to fix to get approved.

### REQUIRED CHANGES: ⚠️ 

- [ ] 1/14 tests is failing. Give it a quick fix.
Screenshot from 2021-04-14 03-21-38


### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Ping me on slack for a chit-chat 🆘  Roy Mukuye Or mention me in this PR

**Comment by FdI96** [comment]
> # STATUS: CHANGES REQUIRED 🔴 ♻️
> ## Hey Happy Coders, 👋🏽
> **Thanks for implementing the changes requested earlier on**. However, there is one more issue to fix to get approved.
> 
> ### REQUIRED CHANGES: ⚠️
> * [ ]  1/14 tests is failing. Give it a quick fix.
>   Screenshot from 2021-04-14 03-21-38
> 
> ### Kindly make all the requested changes and submit another CRR. 💯
> **Cheers 🍹 and Happy coding 💻**
> 
> ## Ping me on slack for a chit-chat 🆘 Roy Mukuye Or mention me in this PR

Its done, thanks.

**Review by descholar-ceo — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @FdI96  , your project is approved :tada: :tada: :tada: 
You have implemented all minimum requirements for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Pull request merged**
